### ISSUE TITLE
Croix x Scramble Bug

### ISSUE THREAD

**Issue by KuromueinaShiro** [DazedMTL/Croix-X-Scramble#1]
There is a bug in chapter 7 which makes it impossible to enter chapter 7 ,the bug is a black screen,accept

**Comment by dazedanon** [comment]
Need a screenshot or save.

**Comment by KuromueinaShiro** [comment]
> Perlu tangkapan layar atau simpan.
![Screenshot_20240420-120345](https://github.com/DazedMTL/Croix-X-Scramble/assets/160068870/7459568b-27cb-40a6-9271-226e2b80d60d)
